### ISSUE TITLE
Polylith says I have $CLASSPATH set even though it is not

### ISSUE THREAD

**Issue by miridius** [tengstrand/lein-polylith#16] opened 2018-11-02 14:39 UTC
**Describe the bug**
Any time I run any polylith command in any project, it says "WARNING: You have $CLASSPATH set, probably by accident. It is strongly recommended to unset this before proceeding.", but I do not have this variable set.

**To Reproduce**
```shell
$ lein polylith create w example com.example
$ cd example
$ echo $CLASSPATH

$ lein polylith build

Changed components:
Changed bases:
Changed systems:

Compiling workspace interfaces
WARNING: You have $CLASSPATH set, probably by accident.
It is strongly recommended to unset this before proceeding.
Created /home/miridius/Projects/NutritionIvy/example/interfaces/target/interfaces-1.0.jar
Wrote /home/miridius/Projects/NutritionIvy/example/interfaces/pom.xml
Installed jar and pom into local repo.

Nothing to test
set :last-success in .polylith/time.edn

Execution time: 1.9 seconds
```

**Expected behavior**
The $CLASSPATH error does not show false positives, or, if something is actually wrong it explains the real issue.

**Operating System (please complete the following information):**
 - OS: Linux Mint
 - Version 19

**Versions (please complete the following information):**
 - Leiningen: 2.8.1
 - Java: 1.8.0_181
 - Polylith: 0.2.0 (also reproduceable on 0.1.1)

**Comment by furkan3ayraktar** [comment] 2018-11-05 14:28
The warning mentioned in the issue is not printed by the Polylith plugin, it's printed by Leiningen itself as you can see [here](https://github.com/technomancy/leiningen/blob/aba4502f59e30fd1e63c0530d8fc369683ae6c80/bin/lein#L20) in its source code. You should see the same error if you try to run any other commands using Leiningen.

Leiningen prints this warning if you have an environment variable named $CLASSPATH. Try to see if you have it by running this command on your terminal: 

```echo $CLASSPATH```

I'm closing this issue since it's not related to Polylith plugin.

**Comment by miridius** [comment] 2018-11-09 22:57
Please take a look at the command log from my original post, I did exactly as you suggested and showed that it is not an issue with my classpath:
1. `echo $CLASSPATH` returns nothing.
2. Running other lein commands does not return this error.

Thanks for telling me that this comes from lein though! That makes understanding the problem a lot easier. I had a dig around in the `lein-polylith` source code and I figured out that the root cause is that you are calling `lein compile` in an external process by using clojure.java.shell, and that shell session inherits the environment of the parent process. Since lein polylith is running from within lein, it is getting the lein process' own classpath injected into the shell. So you are basically nesting `lein A --> sh --> lein B` and lein B is picking up on lein A's classpath.

I injected the following code into `leiningen.polylith.cmd.compile` to confirm this:
```clojure
(defn print-inner-sh-classpath []
  (->> (shared/sh "env")
       (str/split-lines)
       (filter #(str/includes? % "CLASSPATH"))
       println))
```

And sure enough it prints the following:
```clojure
(CLASSPATH=/home/miridius/.lein/self-installs/leiningen-2.8.1-standalone.jar)
```

This is the classpath that the `lein` script itself adds (the exact same script which complains when the classpath is already set). So running `lein` from within `sh` from within `lein` will *always* give this error. What surprises me is why it's not happening to other users of polylith, perhaps the Mac OS version of lein does not set its own CLASSPATH?

You can reproduce the issue really simply on Linux like this:
```shell
$ lein repl
nREPL server started on port 46861 on host 127.0.0.1 - nrepl://127.0.0.1:46861
REPL-y 0.3.7, nREPL 0.2.12
Clojure 1.8.0
OpenJDK 64-Bit Server VM 1.8.0_181-8u181-b13-1ubuntu0.18.04.1-b13
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> (require '[clojure.java.shell :as shell])
nil
user=> (shell/sh "lein" "version")
{:exit 0, :out "WARNING: You have $CLASSPATH set, probably by accident.\nIt is strongly recommended to unset this before proceeding.\nLeiningen 2.8.1 on Java 1.8.0_181 OpenJDK 64-Bit Server VM\n", :err ""}
```

**Comment by furkan3ayraktar** [comment] 2018-11-12 00:04
Thank you @miridius for investigating this more. Here are my thoughts on the issue after spending several hours on it.
 
I've tried it with several __Linux__ versions and with different __Oracle__ and __OpenJDK__ versions, it seems to be like the issue happens on _Linux_ regardless of distribution or _JVM_. I've also tried to find a clue why _Leiningen_ does not include ``CLASSPATH`` on _MacOS_ but I couldn't find.

Even though I still think this is not something we should solve within _the Polylith plugin_, since it is not a problem/bug caused by the plugin. Although, we need to handle the issue until the real issue is found either in _Leiningen_, _JVM_, or _Clojure_, or maybe somewhere else I can't think of now. I'm also hesitant about adding/fixing things within the code without knowing the exact reason of the problem. We might introduce more problems as well in the future.

__P.S.__ I've also found an example about ```clojure.java.shell/sh``` function in the Clojure documentation, where the ``CLASSPATH`` variable is removed while calling the ```sh``` function within a _Leiningen_ context. You can find the example [here](
https://clojuredocs.org/clojure.java.shell/sh#example-5bbe2016e4b00ac801ed9ecf). This does not prove or show anything but it's good to see someone else doing the same thing for some reason :).

What do you think about this @tengstrand and @Misophistful? I would like to hear your thoughts about this particular issue.

**Closed as completed** 2018-11-19 16:10 UTC
Labels: enhancement
